const fs=require('fs'),path=require('path');
const dir=__dirname;
const data={
'6443467a-6d47-4de4-a59f-02131a0b6718': ['# 图片原文提取：任务状态机测试用例','## 功能说明','7.1 最大架构变化：破坏性操作由阻塞执行改为异步任务+状态机。','## 做了什么','- src/service/task/ 新建状态机：pending -> running -> verifying -> success/failed。','- SQLite 持久化、checkpoint 恢复、resource lock、timeout；格式化/建池/RAID/USB 均接入。','- 7.0 sync.Once DB 初始化永久失败改为 mutex+nil 重试自愈。','## 新增 API','| 端点 | 方法 | 说明 |','| --- | --- | --- |','| /v1/storage/task/query | GET | 查询任务列表 |','| /v1/storage/task/:id | GET | 查询单个任务详情 |','| /v1/storage/task/latest?target= | GET | 按目标查最新任务 |','| /health | GET | 服务健康检查 |','> 图片下方测试用例表未拍到。'],
'dd358ff1-98d1-47f3-8abf-72eb78d85ffd': ['# 图片原文提取：任务状态机测试用例表','| 编号 | 模块 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- | --- |','| TASK-001 | 任务状态机 | 并发状态更新不倒退 | P0 | 状态不倒退，version 单调递增 |','| TASK-002 | 任务状态机 | 任务断点恢复（kill-9 -> 重启） | P0 | checkpoint 续执，不残留半成品 RAID/LV |','| TASK-004 | 任务状态机 | 格式化双校验/资源锁互斥 | P0 | 第二请求被拒绝 |','| TASK-005 | 任务状态机 | CodedError 结构化返回 | P1 | code、retryable:false，错误码稳定 |','| TASK-006 | 任务状态机 | SIGTERM 优雅退出 30s | P1 | worker 停止接新任务，30s 内退出 |','| TASK-008 | 任务状态机 | DB 不可用后自愈 | P0 | DB 恢复后任务管理器自动可用 |'],
'b9ae027c-ca75-4089-b9bc-7f73f114e6e6': ['# 图片原文提取：存储卷测试用例','## 功能说明','格式化保护 fail-closed；waiting_io 状态机检测 I/O 活跃后再格式化。','## 做了什么','- 卷创建/格式化/删除/扩容任务化。','- 任意挂载（含 btrfs 子卷）直接拒绝，不执行 umount/mkfs。','- 活跃 I/O 每 5s 轮询，静默后 running；双因子占用检测；btrfs 漂移检测。','## 重启恢复场景','| 场景 | 预期 |','| --- | --- |','| 设备在目标路径 | 恢复成功，不重复格式化 |','| 目标路径被其他设备占用 | 失败 -> mount_path_busy |','| 设备在其他路径 | 失败 -> device_mounted_elsewhere |','| Btrfs 根和子卷在线 | 视为成功 |','| 仅子卷在线 | 拒绝，保护在线子卷 |'],
'd7981fff-5d6b-4c5d-935f-299af65123e2': ['# 图片原文提取：存储池测试用例','## 功能说明','存储池创建/删除/扩容/缩容任务化，可恢复可查询；挂载采用幂等恢复。','## 做了什么','- verifier 检查 VG/LV/mount，已完成跳过，未完成继续，失败 fail-closed。','- 可用池扫描、同名卷组冲突消解、外来卷组收编；删除按钮全局禁用。','- TRAID -> TRAID+ 迁移；删除后无残留 md/VG/LV。','## RAID 级别参数矩阵','| RAID | 最少磁盘 |','| --- | --- |','| RAID0 | 2 |','| RAID1 | 2 |','| RAID5 | 3 |','| RAID6 | 4 |','| RAID10 | 4 |','| TRAID | 3+ |'],
'61037bdd-d93a-4a97-b54e-9d30b8be2331': ['# 图片原文提取：设备身份与配置漂移','## 功能说明','磁盘身份由 Serial -> PTUUID -> Model+Device+Size 三层匹配；启动后对账 volume.conf。','## 做了什么','- Serial 强匹配无告警；PTUUID 是 Serial 为空时的第二道保护。','- 三元弱匹配产生 DeviceIdentityWarning；旧 hotspare.conf 自动回填。','- /disk/DeviceIdentityWarnings 暴露告警；ext4/xfs 自动恢复，btrfs 只告警。','- 物理拔盘正常跳过，不计漂移。','> 测试用例表从图片底部开始，未拍到。'],
'8b0abca5-ed73-4888-8e1c-fc42b2710709': ['# 图片原文提取：设备身份与卷对账补充','## 场景 C：建池固定磁盘身份','任务 payload 保存 /dev/disk/by-id/ata-XXX，设备名变化仍指向正确物理盘。','## 场景 D：启动后卷对账','读取 /proc/mounts 和 volume.conf；设备缺失跳过；ext4/xfs 自动 mount；btrfs 只告警；结果在 /health.volume-config。','## 告警与升级自愈','Serial/PTUUID 不可用时产生 DeviceIdentityWarning；旧 hotspare.conf 升级后从 diskcache 回填。','## 测试磁盘准备','| 类型 | 数量 | 用途 |','| --- | --- | --- |','| 同型号 SATA HDD | 3 | 三元匹配 |','| 同型号 SSD | 2 | PTUUID 匹配 |','| USB-SATA 桥接盘 | 1 | Serial 为空 |','| NVMe+外接盒 | 1 | smartctl 兼容 |'],
'5f9aeda0-b5b3-40fa-bd3f-3ab6f46c9e56': ['# 图片原文提取：热备盘设备身份','| 编号 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- |','| ID-001 | 设备名漂移后凭 Serial 识别 | P0 | 热备盘不进空闲列表，无告警 |','| ID-002 | 同型号不同 Serial 不误判 | P0 | 不因型号/容量混淆 |','| ID-003 | USB 桥接盘走 PTUUID | P0 | 设备名变化仍识别，无告警 |','| ID-004 | 全新盘三元弱匹配 | P1 | 识别但产生告警 |','| ID-005 | 旧配置回填 Serial/PTUUID | P0 | 自动写回配置 |','| ID-006 | 旧配置盘拔走 | P1 | 清理失效 section，不 panic |','| ID-007 | Serial 强匹配 | P2 | 告警列表为空 |','## 二、Flashcache 缓存盘设备身份','> 图片在此标题处结束。'],
'd9dd0814-da2f-47eb-8ddb-9866445b925f': ['# 图片原文提取：匹配逻辑速查','输入：/dev/sdX、Serial、Model、Size、PTUUID。','1. Serial 强匹配 -> 确认身份，不告警。','2. PTUUID 匹配（7.1 新增） -> 确认身份，不告警。','3. 三元弱匹配 -> 确认身份并产生 DeviceIdentityWarning。','## 同型号多盘风险矩阵','| 场景 | 走哪层 | 风险 |','| --- | --- | --- |','| 正常 SATA x3 | Serial | 安全 |','| USB 桥接 x3 | PTUUID | 安全（7.1） |','| 全新未分区 x3 | 三元弱匹配 | P0，无法区分 |','| 同型号混用 | ②或③ | 行为不可预测 |'],
'8f63a966-c79c-4103-9e6c-464618f53454': ['# 图片原文提取：Context 生命周期测试','## 验证命令','ps aux | grep -E defunct|z；curl /debug/pprof/goroutine；lsof StorageManager.pid；ps aux | grep mdadm|mkfs|lvm。','| 编号 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- |','| CTX-001 | 操作取消后子命令收到取消 | P0 | kill 子命令，释放锁，无僵尸 |','| CTX-002 | 外部命令超时 kill | P0 | 无孤儿进程，HTTP 不阻塞 |','| CTX-003 | 关闭时任务取消/重启恢复 | P1 | 标记中断并恢复 |','| CTX-004 | Unix HTTP 优雅退出 | P0 | Graceful Shutdown，不接新连接 |','| CTX-005 | 生命周期资源关闭 | P0 | 无 goroutine/FD/SQLite/LVM 泄漏 |','| CTX-006 | 外接设备 Shell 收口 | P1 | 使用 Go exec.CommandContext |'],
'96927e65-857c-4b1b-bf25-94a0852caf9a': ['# 图片原文提取：RAID 测试用例','## 功能说明','RAID 修复接入任务状态机；健康判断纯函数；热备自动故障转移；分区对齐和 md9 修复。','## 做了什么','- running -> verifying -> success，可中断恢复。','- 拔盘 -> degraded -> 热备盘加入 -> md rebuild。','- 蜂鸣器自动关闭；分区不重叠 + 512K 对齐；mdops 查询目标阵列 p2。','- 多阵列进度独立；移除 degraded 判断。','## 验证命令','cat /proc/mdstat；mdadm --detail /dev/mdX；parted /dev/sdX print；echo check > /sys/block/mdX/md/sync_action。','> 图片底部测试用例表未完整拍到。'],
'7cfa1ff1-b1d8-4d65-b2d1-87f4bcf945e4': ['# 图片原文提取：系统盘测试用例','## 安全前置检查','cat /proc/mdstat | grep md9；mdadm --detail /dev/md9 | grep State|Active|Working。md9 至少 2 个有效成员。','| 编号 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- |','| SYS-001 | 系统盘迁移（md9 无损） | P0 | 任务可追踪，指纹更新，md9 无损，GRUB 成功 |','| SYS-002 | 系统盘删除（md9>=2） | P0 | 任务化，指纹刷新，md9>=2 |','| SYS-003 | GRUB 安装可取消 | P0 | 无残留，分区+RAID 完整 |','| SYS-004 | USB 禁止新增系统盘 | P1 | 返回 dest disk is usb |'],
'640523e1-4bc9-4cf4-b54b-67ab0d864a8e': ['# 图片原文提取：容量水位策略','## 功能说明','四级水位线 70/85/90/95% + clamp 剩余空间，预留 Btrfs 元数据和 RAID reshape。','- 70% 展示趋势；85% storage_watermark_alert；90% storage_watermark_restrict；95% 只允许释放/只读。','- 90% clamp(总量×10%，≥50G，≤500G)；95% clamp(总量×5%，≥20G，≤200G)。','## 四级水位模型','| 水位 | 行为 |','| --- | --- |','| 70% | 展示趋势 |','| 85% | 主动告警 |','| 90% | 限制高风险操作 |','| 95% | 只允许释放/只读 |'],
'f28e9f43-05dd-4f48-86c9-78da84019465': ['# 图片原文提取：磁盘管理测试用例','## 验证命令','smartctl -t short /dev/sdX','| 编号 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- |','| DISK-001 | 磁盘格式化任务化 | P0 | running -> verifying -> success |','| DISK-002 | 并发格式化互斥 | P1 | 第二请求被资源锁阻塞 |','| DISK-003 | 安全擦除 DiskErase | P1 | checkpoint 持久化，fail-closed |','| DISK-005 | 格式化 md9 成员盘 | P0 | Preflight 拒绝，md9>=2 |','| DISK-006 | 格式化中断重启恢复 | P0 | checkpoint 恢复或安全失败 |','| DISK-007 | SMART 检测 | P0 | 任务可恢复 |','| DISK-008 | Data Scrubbing | P1 | 进度可查询，不影响 I/O |','| DISK-009 | 性能基准 | P1 | 数据合理，is_working |','| LOCKED-001 | 空 NAS 快照兼容 | P0 | 返回 [] 而非 null |'],
'91e968dd-4bc8-4770-82e0-4bbd03ee2599': ['# 图片原文提取：安全与权限测试用例','## 功能说明','Shell -> Go 执行器收口，修复密码泄露、进程自杀、权限校验。','## 做了什么','- 密码改 stdin；关闭时不误杀 mdadm；非 admin 返回 403；内部接口外部 curl 返回 403。','- nginx 拦截多斜杠；code_num 统一 60；私有 ACL 不走 Shell 管道。','> 测试用例表从照片下方开始，未拍到。'],
'b9986875-2918-4d7d-b885-650f8912cff7': ['# 图片原文提取：接口兼容性测试用例','## 功能说明','7.1 HTTP API 返回结构与 7.0 兼容，新增端点不影响旧端点，API 路径不变。','## 做了什么','- 原有 JSON 字段/类型/嵌套不变；新增 /v1/storage/task/query、/v1/storage/task/latest、/health、/disk/DeviceIdentityWarnings。','- RPC/proto 无破坏性变更；msgbus 兼容；7.0 volume.conf/hotspare.conf/pool_*.conf 可解析。','- Swagger：ExtStorageDeviceController(17)、LvmCacheController(10)、HotSpareDiskController(6)。','> API 端点清单只拍到标题和首行。'],
'53fe3cd4-05c6-4c93-85d0-419f99073d20': ['# 图片原文提取：升级与回退异常场景','## 慢盘/IO Error 模拟','| 场景 | 模拟方式 | 预期 |','| --- | --- | --- |','| 慢盘 | echo 1000 > /sys/block/sdX/device/timeout | 任务超时后失败 |','| 坏道 | dd if=/dev/urandom of=/dev/sdX ... -> SMART | 检测到坏道 |','| IO Error | echo offline > /sys/block/sdX/device/state | 明确报错 |','## 测试用例','| UPGRADE-001 | 7.0 -> 7.1 升级 | P0 | 池卷热备缓存保留 |','| UPGRADE-002 | 7.1 -> 7.0 回退 | P0 | 配置可读，SQLite 透明 |','| ROBUST-001 | 断电恢复 | P0 | 正常启动，配置不损坏 |','| ROBUST-002 | 拔盘 degraded 修复 | P0 | md degraded，修复 Clean |','| ROBUST-003 | 慢盘/坏道/IO Error | P1 | 超时明确，服务不卡死 |','| ROBUST-004 | iSCSI 断网30s恢复 | P1 | 连接可恢复 |','| ROBUST-005 | 24h 长稳 | P1 | 无泄漏，SQLite 不膨胀 |'],
'a00eee17-39d1-46c8-94de-dc1fe609154f': ['# 图片原文提取：SSD 缓存测试用例','## 功能说明','SSD 缓存增删改任务化；Flashcache 身份 Serial -> PTUUID -> 块名；HyperCache 重启自动恢复。','## 做了什么','- 创建/删除任务状态机；checkpoint 恢复；RemoveCacheLV 恢复路径修复。','## 验证命令','dmsetup status；lvs -a | grep cache；cat /proc/flashcache/stats 2>/dev/null。','> 测试用例表从照片下方开始。'],
'937ede40-ffb1-4028-bea8-0654ecf64f29': ['# 图片原文提取：SSD 缓存测试用例表','| 编号 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- |','| CACHE-001 | 添加/删除 SSD 缓存任务化 | P1 | 任务可追踪，缓存生效，删除修复 |','| CACHE-002 | 创建中断重启恢复 | P1 | checkpoint 恢复，无中间状态 |','| CACHE-003 | 缓存盘身份三层匹配 | P0 | Serial/PTUUID/块名兜底并告警 |','| CACHE-004 | HyperCache 重启任务恢复 | P1 | 自动恢复，不需重建 |'],
'43405f65-0e15-4557-9305-c3f4f147fd07': ['# 图片原文提取：iSCSI 虚拟磁盘测试用例','## 功能说明','LUN 挂载/格式化任务化、10s 版本化快照、映射漂移检测、启动对账自动恢复。','## 做了什么','- 10s 快照 + 前端 5s 轮询；漂移返回 iscsi_mapping_changed。','- 重启后配置 LUN 自动挂载，显式卸载的不重挂；stale/refreshing 禁用按钮；密码不明文。','> 测试用例表只拍到表头和第一行。'],
'2589d08e-98eb-4a16-a9ee-be749dd965a9': ['# 图片原文提取：iSCSI 测试用例表','| 编号 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- |','| ISCSI-001 | iSCSI 实时同步（10s快照+5s轮询） | P1 | 快照更新，P99<1ms |','| ISCSI-002 | 映射漂移 -> iscsi_mapping_changed | P0 | 返回错误并提示刷新 |','| ISCSI-003 | stale/refreshing 禁用操作 | P1 | 按钮禁用，toast 等待 |','| ISCSI-004 | 启动对账恢复 | P1 | 配置 LUN 自动挂载，显式卸载不重挂 |','| ISCSI-005 | 无 Target 空状态 | P2 | 不误报，空状态正常 |','| ISCSI-006 | LUN 格式化任务化 | P1 | 变化时中断，LUN 可用 |'],
'e3fa48d1-e876-4b04-8aaa-3e15282233a9': ['# 图片原文提取：USB/eSATA 外接存储测试用例','## 图片顶部改动','- umountUsb 异步竞态修复；连续 5 次切换 FS 不报 partitions in use。','- ntfs/vfat 权限 gid=allusers+770。','- 外接设备走 Go exec.CommandContext，不走 sh -c。','| 编号 | 标题 | 优先级 | 预期结果 |','| --- | --- | --- | --- |','| HOTPLUG-001 | USB 插入4s防抖 | P1 | 拓扑刷新，版本递增 |','| HOTPLUG-002 | USB 热移除 | P1 | 快照正确更新 |','| HOTPLUG-003 | 连续5次插拔 | P2 | 版本单调递增 |','| USB-001 | USB 格式化全部文件系统 | P0 | running -> verifying -> success |','| USB-002 | 连续5次切换 FS | P1 | 全成功，无竞态 |','| USB-003 | ntfs/vfat gid+770 | P2 | 挂载参数正确 |','| USB-004 | 格式化中列表 | P1 | 无502，lsblk不阻塞 |']
};
for(const [base,lines] of Object.entries(data)){const file=fs.readdirSync(dir).find(f=>f.endsWith('-'+base+'.md'));if(!file)throw Error('missing '+base);const img='../'+base+'.jpg';fs.writeFileSync(path.join(dir,file),['# 图片原文提取：'+base,'','![原图]('+img+')','',...lines,''].join('\r\n'),'utf8');}
console.log('filled '+Object.keys(data).length+' missing docs');
