const fs=require('fs'),path=require('path');
const dir=__dirname;
const docs=fs.readdirSync(dir).filter(f=>/^\d{2}-.*\.md$/.test(f)).sort();
const labels={SEC:'security',ACL:'security',API:'api-compat',CACHE:'ssd-cache',FC:'flashcache-identity',CFG:'config',CTX:'context',DI:'device-identity',ID:'hotspare-identity',WARN:'identity-warning',DISK:'disk',LOCKED:'disk',FORMAT:'volume',VOL:'volume',HOTPLUG:'usb-esata',USB:'usb-esata',HW:'nas-binding',VC:'volume-drift',ISCSI:'iscsi',POOL:'pool',RAID:'raid',ROBUST:'upgrade-robust',UPGRADE:'upgrade-robust',SYS:'system-disk',TASK:'task-state',WM:'watermark'};
function groupsFor(s){const out=new Set();for(const m of s.matchAll(/\b([A-Z]+)-\d{3}\b/g)){if(labels[m[1]])out.add(labels[m[1]]);}if(!out.size){const t=s.toLowerCase();if(t.includes('iscsi'))out.add('iscsi');else if(t.includes('usb')||t.includes('esata'))out.add('usb-esata');else if(t.includes('ssd')||t.includes('flashcache'))out.add('ssd-cache');else if(t.includes('raid'))out.add('raid');else if(t.includes('pool'))out.add('pool');else if(t.includes('volume'))out.add('volume');else out.add('section-only');}return [...out];}
const buckets={},cases=new Map(),pri={P0:0,P1:0,P2:0};
for(const file of docs){const s=fs.readFileSync(path.join(dir,file),'utf8');const ids=[...new Set([...s.matchAll(/\b(?:[A-Z]+-\d{3}|LOCKED-001)\b/g)].map(x=>x[0]))];for(const id of ids){const p=(s.match(new RegExp('\\b'+id+'\\b[\\s\\S]{0,220}?\\b(P[0-2])\\b'))||[])[1]||'unlocated';if(p!=='unlocated')pri[p]++;cases.set(id,{id,source:file,priority:p});}for(const g of groupsFor(s)){if(!buckets[g])buckets[g]=[];buckets[g].push({file,ids});}}
const out=[];out.push('# TOS 7.1 Photo Extraction - All Modules','','> Scope: 41 local JPG images; one Markdown document per image. Cropped areas are marked and not guessed.','','## Completeness','','| Item | Result |','| --- | --- |','| Images | '+docs.length+' |','| Single-image Markdown | '+docs.length+' |','| Unique case IDs | '+cases.size+' |','| Locatable priorities | P0 '+pri.P0+'; P1 '+pri.P1+'; P2 '+pri.P2+' |','','## Module Array','','| Module | Image numbers | Visible case IDs | Documents |','| --- | --- | --- | --- |');
for(const [g,items] of Object.entries(buckets).sort()){const imgs=[...new Set(items.map(x=>x.file.slice(0,2)))].join(', ');const ids=[...new Set(items.flatMap(x=>x.ids))].join(', ');const links=[...new Set(items.map(x=>'['+x.file+']('+x.file+')'))].join('<br>');out.push('| '+g+' | '+imgs+' | '+(ids||'section text only')+' | '+links+' |');}
out.push('','## Image Index','','| No. | Document | Visible IDs/section |','| --- | --- | --- |');
for(const file of docs){const s=fs.readFileSync(path.join(dir,file),'utf8');const ids=[...new Set([...s.matchAll(/\b(?:[A-Z]+-\d{3}|LOCKED-001)\b/g)].map(x=>x[0]))];const h=(s.match(/^# .+$/m)||[file])[0].replace(/^# /,'');out.push('| '+file.slice(0,2)+' | ['+file+']('+file+') | '+(ids.join(', ')||h)+' |');}
out.push('','## Case ID List','','| ID | Priority | Source |','| --- | --- | --- |');for(const c of [...cases.values()].sort((a,b)=>a.id.localeCompare(b.id)))out.push('| '+c.id+' | '+c.priority+' | ['+c.source+']('+c.source+') |');
fs.writeFileSync(path.join(dir,'all_modules_summary.md'),out.join('\r\n')+'\r\n','utf8');fs.writeFileSync(path.join(dir,'final-check.json'),JSON.stringify({images:docs.length,markdown:docs.length,uniqueCaseIds:cases.size,priority:pri,modules:Object.fromEntries(Object.entries(buckets).map(([k,v])=>[k,[...new Set(v.map(x=>x.file))].length]))},null,2),'utf8');console.log('summary generated',docs.length,cases.size,Object.keys(buckets).length);
